### ISSUE TITLE
Feature Request: Open Firefox (with container)

### ISSUE THREAD

**Issue by davizucon** [kangaechu/aws-vault-alfred-workflow#3]
Hello,
   Instead of chrome, can open Firefox (open -a firefox -g <url>)?
   And be would even better in future if it's open in specific container, Firefox [WIP](https://github.com/mozilla/multi-account-containers/issues/365)

**Comment by kangaechu** [comment]
Thank your opening this issue!
from 0.0.4, this tool supports firefox.
